/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.component;

import java.awt.Color;
import java.awt.Dimension;

/**
 *
 * @author 84975
 */
public class PanelTenSanPham extends javax.swing.JPanel {

    /**
     * Creates new form PanelTenSanPham
     */
    public PanelTenSanPham() {
        initComponents();
        config();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SPChuaCo = new gui.swing.textfield.MyTextField();
        SPDaCo = new gui.swing.textfield.MyComboBox();

        setLayout(new java.awt.CardLayout());

        SPChuaCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPChuaCoActionPerformed(evt);
            }
        });
        add(SPChuaCo, "card2");

        SPDaCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPDaCoActionPerformed(evt);
            }
        });
        add(SPDaCo, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void SPChuaCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPChuaCoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SPChuaCoActionPerformed

    private void SPDaCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPDaCoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SPDaCoActionPerformed
    
    public void config(){
        this.setOpaque(false);
        SPChuaCo.setBorderLine(true);
        
        
        SPDaCo.setBorderLine(true);
        SPDaCo.setBorderRadius(10);
        
        SPDaCo.addItem("Sản phẩm 1");
    }
    
    public void setTypeSP(boolean b){
        if(b){
            SPDaCo.setVisible(false);
            SPChuaCo.setVisible(true);
        }else{
            SPChuaCo.setVisible(false);
            SPDaCo.setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gui.swing.textfield.MyTextField SPChuaCo;
    private gui.swing.textfield.MyComboBox SPDaCo;
    // End of variables declaration//GEN-END:variables
}
