package gui.component;

import entity.NhanVien;

public class PanelTabThongTinNV extends javax.swing.JPanel {

    private NhanVien nhanVien;

    public PanelTabThongTinNV(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
        initComponents();
        HandlerData();
    }

    private void HandlerData() {
        lblValueMaNhanVien.setText(nhanVien.getMaNhanVien());

        String gioiTinh = nhanVien.isGioiTinh() == true ? "Nữ" : "Nam";
        lblValueGioiTinh.setText(gioiTinh);

        lblValueNgaySinh.setText(nhanVien.getMaNhanVien());

        lblValueSDT.setText(nhanVien.getSoDienThoai());
        lblValueEmail.setText(nhanVien.getEmail());

        String caLam = nhanVien.getCaLam().getGioBatDau() + "-" + nhanVien.getCaLam().getGioKetThuc();
        lblValueCaLam.setText(caLam);
        lblValueLoaiNhanVien.setText(nhanVien.getLoaiNhanVien().getTenLoaiNV());

        String diaChi = nhanVien.getDiaChi().getSoNha() + ", " + nhanVien.getDiaChi().getTenDuong() + ", " + nhanVien.getDiaChi().getXaPhuong()
                + ", " + nhanVien.getDiaChi().getQuanHuyen() + ", " + nhanVien.getDiaChi().getTinhThanh();
        lblValueDiaChi.setText(diaChi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblMaNhanVien = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblCaLam = new javax.swing.JLabel();
        lblLoaiNhanVien = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblValueMaNhanVien = new javax.swing.JLabel();
        lblValueGioiTinh = new javax.swing.JLabel();
        lblValueNgaySinh = new javax.swing.JLabel();
        lblValueSDT = new javax.swing.JLabel();
        lblValueEmail = new javax.swing.JLabel();
        lblValueCaLam = new javax.swing.JLabel();
        lblValueLoaiNhanVien = new javax.swing.JLabel();
        lblValueDiaChi = new javax.swing.JLabel();
        lblDiaChi1 = new javax.swing.JLabel();
        lblDiaChi2 = new javax.swing.JLabel();
        lblDiaChi3 = new javax.swing.JLabel();
        lblCaLam1 = new javax.swing.JLabel();
        lblCaLam2 = new javax.swing.JLabel();

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));

        lblMaNhanVien.setBackground(new java.awt.Color(204, 204, 204));
        lblMaNhanVien.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblMaNhanVien.setText("Mã nhân viên");

        lblGioiTinh.setBackground(new java.awt.Color(204, 204, 204));
        lblGioiTinh.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblGioiTinh.setText("Giới tính");

        lblNgaySinh.setBackground(new java.awt.Color(204, 204, 204));
        lblNgaySinh.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblNgaySinh.setText("Ngày sinh");

        lblSDT.setBackground(new java.awt.Color(204, 204, 204));
        lblSDT.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblSDT.setText("SDT");

        lblEmail.setBackground(new java.awt.Color(204, 204, 204));
        lblEmail.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblEmail.setText("Email");

        lblCaLam.setBackground(new java.awt.Color(204, 204, 204));
        lblCaLam.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblCaLam.setText("Ca làm");

        lblLoaiNhanVien.setBackground(new java.awt.Color(204, 204, 204));
        lblLoaiNhanVien.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblLoaiNhanVien.setText("Loại nhân viên");

        lblDiaChi.setBackground(new java.awt.Color(204, 204, 204));
        lblDiaChi.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblDiaChi.setText("Địa chỉ");

        lblValueMaNhanVien.setBackground(new java.awt.Color(204, 204, 204));
        lblValueMaNhanVien.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblValueMaNhanVien.setText("123");

        lblValueGioiTinh.setBackground(new java.awt.Color(204, 204, 204));
        lblValueGioiTinh.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblValueGioiTinh.setText("Nam");

        lblValueNgaySinh.setBackground(new java.awt.Color(204, 204, 204));
        lblValueNgaySinh.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblValueNgaySinh.setText("01-01-2021");

        lblValueSDT.setBackground(new java.awt.Color(204, 204, 204));
        lblValueSDT.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblValueSDT.setText("0123456789");

        lblValueEmail.setBackground(new java.awt.Color(204, 204, 204));
        lblValueEmail.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblValueEmail.setText("email@gmail.com");

        lblValueCaLam.setBackground(new java.awt.Color(204, 204, 204));
        lblValueCaLam.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblValueCaLam.setText("08:00-13:00");

        lblValueLoaiNhanVien.setBackground(new java.awt.Color(204, 204, 204));
        lblValueLoaiNhanVien.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblValueLoaiNhanVien.setText("Lễ Tân");

        lblValueDiaChi.setBackground(new java.awt.Color(204, 204, 204));
        lblValueDiaChi.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblValueDiaChi.setText("12, Le Van Bao, Go Vap, TP Ho Chi Minh");

        lblDiaChi1.setBackground(new java.awt.Color(204, 204, 204));
        lblDiaChi1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblDiaChi1.setText("Xã/Phường");

        lblDiaChi2.setBackground(new java.awt.Color(204, 204, 204));
        lblDiaChi2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblDiaChi2.setText("Quận/Huyện");

        lblDiaChi3.setBackground(new java.awt.Color(204, 204, 204));
        lblDiaChi3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblDiaChi3.setText("Tỉnh/Thành phố");

        lblCaLam1.setBackground(new java.awt.Color(204, 204, 204));
        lblCaLam1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblCaLam1.setText("Số Căn cước");

        lblCaLam2.setBackground(new java.awt.Color(204, 204, 204));
        lblCaLam2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblCaLam2.setText("Số Căn cước");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblLoaiNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiaChi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiaChi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDiaChi3))
                        .addGap(38, 38, 38)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblValueDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblValueLoaiNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCaLam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSDT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(lblCaLam1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblValueCaLam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblValueEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                            .addComponent(lblValueSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblValueNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblValueGioiTinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblValueMaNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCaLam2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValueMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValueGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValueNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValueSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValueEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaLam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValueCaLam, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaLam1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCaLam2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoaiNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValueLoaiNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValueDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDiaChi1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDiaChi2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDiaChi3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCaLam;
    private javax.swing.JLabel lblCaLam1;
    private javax.swing.JLabel lblCaLam2;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblDiaChi1;
    private javax.swing.JLabel lblDiaChi2;
    private javax.swing.JLabel lblDiaChi3;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblLoaiNhanVien;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblValueCaLam;
    private javax.swing.JLabel lblValueDiaChi;
    private javax.swing.JLabel lblValueEmail;
    private javax.swing.JLabel lblValueGioiTinh;
    private javax.swing.JLabel lblValueLoaiNhanVien;
    private javax.swing.JLabel lblValueMaNhanVien;
    private javax.swing.JLabel lblValueNgaySinh;
    private javax.swing.JLabel lblValueSDT;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
