/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.component;

/**
 *
 * @author Hao
 */
public class PanelSuaPDP extends javax.swing.JPanel {
    /**
     * Creates new form PanelSuaPDP
     */
    public PanelSuaPDP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSuaPhieuDP = new javax.swing.JPanel();

        pnlSuaPhieuDP.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlSuaPhieuDPLayout = new javax.swing.GroupLayout(pnlSuaPhieuDP);
        pnlSuaPhieuDP.setLayout(pnlSuaPhieuDPLayout);
        pnlSuaPhieuDPLayout.setHorizontalGroup(
            pnlSuaPhieuDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );
        pnlSuaPhieuDPLayout.setVerticalGroup(
            pnlSuaPhieuDPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSuaPhieuDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSuaPhieuDP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlSuaPhieuDP;
    // End of variables declaration//GEN-END:variables
}
