/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui.component;

import entity.PhieuDatPhong;
import gui.swing.event.EventTabSelected;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Hao
 */
public class PhieuDatPhongDetail extends javax.swing.JPanel {
    
    private PhieuDatPhong phieuDatPhong;
    private PanelThongTinPDP pnlThongTinPDP;
    private PanelSuaPDP pnlSuaPDP;

    /** Creates new form PhieuDatPhongDetail */
    public PhieuDatPhongDetail(PhieuDatPhong phieuDatPhong) {
        this.phieuDatPhong = phieuDatPhong;
        initComponents();
        buildDisplay();
    }

     private void buildDisplay() {
        pnlThongTinPDP= new PanelThongTinPDP(phieuDatPhong);
        pnlSuaPDP = new PanelSuaPDP(phieuDatPhong);
        createTabButton();
    }

    private void createTabButton() {
        tabButton.setEvent(new EventTabSelected() {
            @Override
            public boolean selected(int index, boolean selectedTab) {
                if(index == 0) {
                    showTab(pnlThongTinPDP);
                }
                else if(index == 1) {
                    showTab(pnlSuaPDP);
                }
                tabButton.check();
                return true;
            }
        });
        tabButton.addTabButtonItem("Thông tin");
        tabButton.addTabButtonItem("Sửa");
        pnlBottom.add(pnlThongTinPDP);
        pnlBottom.add(pnlSuaPDP);
    }
    
    private void showTab(Component com) {
        pnlBottom.removeAll();
        pnlBottom.add(com);
        pnlBottom.repaint();
        pnlBottom.revalidate();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBottom = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        btnIn = new javax.swing.JButton();
        tabButton = new gui.swing.panel.TabButton();

        setLayout(new java.awt.BorderLayout());

        pnlBottom.setBackground(new java.awt.Color(255, 255, 255));
        add(pnlBottom, java.awt.BorderLayout.CENTER);

        pnlTop.setBackground(new java.awt.Color(255, 255, 255));
        pnlTop.setPreferredSize(new java.awt.Dimension(717, 80));

        btnIn.setBackground(new java.awt.Color(255, 255, 255));
        btnIn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnIn.setText("IN");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });

        tabButton.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap(688, Short.MAX_VALUE)
                .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(tabButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        add(pnlTop, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        printRecord(pnlBottom);
    }//GEN-LAST:event_btnInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIn;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlTop;
    private gui.swing.panel.TabButton tabButton;
    // End of variables declaration//GEN-END:variables
    private void printRecord(JPanel panel){
            //Create printerJob Here
            PrinterJob printerJob = PrinterJob.getPrinterJob();

            printerJob.setJobName("Print Record");
            printerJob.setPrintable(new Printable() {
                @Override
                public int print(Graphics arg0, PageFormat arg1, int arg2) throws PrinterException {
                    if(arg2>0){
                        return Printable.NO_SUCH_PAGE;
                    }

                    Graphics2D graphics2D = (Graphics2D) arg0;
                    graphics2D.translate(arg1.getImageableX(), arg1.getImageableY());
                    graphics2D.scale(0.76,1.1);
                    panel.print(graphics2D);
                    return Printable.PAGE_EXISTS;
                }
            });

            boolean returningResult = printerJob.printDialog();
            if(returningResult){
                try{
                    printerJob.print();
                }catch(PrinterException p){
                    JOptionPane.showMessageDialog(this, "Print Error: "+p.getMessage());
                }
            }
    }
}
