package gui.component;

import entity.PhieuDatPhong;
import gui.swing.event.EventTabSelected;
import java.awt.Component;

public class PhieuDatPhongDetail extends javax.swing.JPanel {
    
    private PhieuDatPhong phieuDatPhong;
    private PanelThongTinPDP pnlThongTinPDP;

    /** Creates new form PhieuDatPhongDetail */
    public PhieuDatPhongDetail(PhieuDatPhong phieuDatPhong) {
        this.phieuDatPhong = phieuDatPhong;
        initComponents();
        buildDisplay();
    }

     private void buildDisplay() {
        pnlThongTinPDP= new PanelThongTinPDP(phieuDatPhong);
        createTabButton();
    }

    private void createTabButton() {
        tabButton.setEvent(new EventTabSelected() {
            @Override
            public boolean selected(int index, boolean selectedTab) {
                if(index == 0) {
                    showTab(pnlThongTinPDP);
                }
                else if(index == 1) {
                    showTab(new PanelSuaPDP());
                }
                tabButton.check();
                return true;
            }
        });
        
        tabButton.addTabButtonItem("Thông tin");
        tabButton.addTabButtonItem("Sửa");
        pnlBottom.add(pnlThongTinPDP);
    }
    
    private void showTab(Component com) {
        pnlBottom.removeAll();
        pnlBottom.add(com);
        pnlBottom.repaint();
        pnlBottom.revalidate();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBottom = new javax.swing.JPanel();
        pnlTop = new javax.swing.JPanel();
        tabButton = new gui.swing.panel.TabButton();
        lblTen = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        pnlBottom.setBackground(new java.awt.Color(255, 255, 255));
        pnlBottom.setLayout(new java.awt.BorderLayout());
        add(pnlBottom, java.awt.BorderLayout.CENTER);

        pnlTop.setBackground(new java.awt.Color(255, 255, 255));
        pnlTop.setPreferredSize(new java.awt.Dimension(717, 60));

        tabButton.setBackground(new java.awt.Color(204, 255, 255));

        lblTen.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblTen.setText("Nguyễn Thị Hảo");

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(508, Short.MAX_VALUE))
            .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(tabButton, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE))
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                    .addGap(0, 60, Short.MAX_VALUE)
                    .addComponent(tabButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(pnlTop, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTen;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlTop;
    private gui.swing.panel.TabButton tabButton;
    // End of variables declaration//GEN-END:variables

}
