/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import gui.swing.panel.PanelShadow;
import gui.swing.scrollbar.ScrollBarCustom;
import gui.swing.table.SpinnerEditor;
import gui.swing.table.TableCustom;
import gui.swing.table.TableCustomCheckBox;
import gui.swing.table.TableCustomRadio;
import gui.swing.textfield.MyTextField;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.BorderFactory;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import net.miginfocom.swing.MigLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author 84975
 */
public class GD_CuaSoDatPhong extends JFrame {

    /**
     * Creates new form GD_CuaSoDatPhong
     */
    private TableCustomCheckBox table;
    private JPanel pnlLoc;
    private JPanel pnlDanhSachPhong;
    private JPanel pnlInfo;
    private JPanel pnlAction;
    private String fontName = "sansserif";
    private int fontStyle = Font.PLAIN;
    private int fontSize = 16;
    Color colorBtn = new Color(184, 238, 241);
    
    public GD_CuaSoDatPhong() {
        initComponents();
        setSize(new Dimension(1300,500));
        setLocation(150, 150);
        setTitle("Đổi phòng");
        initForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        MainPanel.setDoubleBuffered(false);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 373, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public void initOldRoomInfo(){
        pnlLoc = new JPanel();
        pnlLoc.setLayout(new MigLayout("","[][]","10[]5"));
        pnlLoc.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.GRAY, 2),
                "Phòng cũ",
                TitledBorder.LEFT,
                TitledBorder.TOP,
                new Font("sansserif", Font.PLAIN, 18),
                Color.GRAY)
        );
        
        JLabel lblTenPhong = new JLabel("Ngày giờ đặt :");
        lblTenPhong.setFont(new Font(fontName, fontStyle, fontSize));
        pnlLoc.add(lblTenPhong, "align left");

        JTextField txtTenPhong = new MyTextField();
        txtTenPhong.setFont(new Font(fontName, fontStyle, fontSize));
        txtTenPhong.setEnabled(false);
        pnlLoc.add(txtTenPhong, "w 100:300:400, h 36! , wrap");
        
        JLabel lblLoaiPhong = new JLabel("Loại phòng :");
        lblLoaiPhong.setFont(new Font(fontName, fontStyle, fontSize));
        pnlLoc.add(lblLoaiPhong, "align left");

        JTextField txtLoaiPhong = new MyTextField();
        txtLoaiPhong.setFont(new Font(fontName, fontStyle, fontSize));
        txtLoaiPhong.setEnabled(false);
        pnlLoc.add(txtLoaiPhong, "w 100:300:400, h 36! , wrap");
        
        JLabel lblGiaPhong = new JLabel("Giá phòng :");
        lblGiaPhong.setFont(new Font(fontName, fontStyle, fontSize));
        pnlLoc.add(lblGiaPhong, "align left");

        JTextField txtGiaPhong = new MyTextField();
        txtGiaPhong.setFont(new Font(fontName, fontStyle, fontSize));
        txtGiaPhong.setEnabled(false);
        pnlLoc.add(txtGiaPhong, "w 100:300:400, h 36! , wrap");
        
        JLabel lblGioDaHat = new JLabel("Giờ đã hát :");
        lblGioDaHat.setFont(new Font(fontName, fontStyle, fontSize));
        pnlLoc.add(lblGioDaHat, "align left");

        JTextField txtGioDaHat = new MyTextField();
        txtGioDaHat.setFont(new Font(fontName, fontStyle, fontSize));
        txtGioDaHat.setEnabled(false);
        
        pnlLoc.add(txtGioDaHat, "w 100:300:400, h 36! , wrap");
        
        JLabel lblTongTienCu = new JLabel("Tổng tiền :");
        lblTongTienCu.setFont(new Font(fontName, fontStyle, fontSize));
        pnlLoc.add(lblTongTienCu, "align left");

        JTextField txtTongTienCu = new MyTextField();
        txtTongTienCu.setFont(new Font(fontName, fontStyle, fontSize));
        txtTongTienCu.setEnabled(false);
        pnlLoc.add(txtTongTienCu, "w 100:300:400, h 36! , wrap");
        
        pnlInfo.add(pnlLoc,"w 30%,h 100%");
        pnlLoc.setBackground(Color.WHITE);  

    }
    
    public void initNewRoom(){
        pnlDanhSachPhong = new JPanel();
        pnlDanhSachPhong.setOpaque(false);
        pnlDanhSachPhong.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.GRAY, 2),
                "Thông tin phòng có thể đổi",
                TitledBorder.LEFT,
                TitledBorder.TOP,
                new Font("sansserif", Font.PLAIN, 18),
                Color.gray)
        );
        pnlDanhSachPhong.setLayout(new MigLayout("","[]","10[]10"));
            pnlDanhSachPhong.setBackground(Color.WHITE);    
//        Object data[][] = { 
//                { "101", "Tran Van Minh", "6000",new JRadioButton() }, 
//                { "102", "Phan Van Tai", "8000",new JRadioButton()  }, 
//                { "101", "Do Cao Hoc", "7000",new JRadioButton() },
//                { "101", "Do Cao Hoc", "7000",new JRadioButton() },
//                { "101", "Do Cao Hoc", "7000",new JRadioButton() },
//                { "101", "Do Cao Hoc", "7000",new JRadioButton() },
//                { "101", "Do Cao Hoc", "7000",new JRadioButton() },
//                { "101", "Do Cao Hoc", "7000",new JRadioButton() },              
//        };
        
//        Object data[][] = { 
//                { "101",0, "Tran Van Minh", "6000",new JRadioButton() }, 
//                { "102",0, "Phan Van Tai", "8000",new JRadioButton()  }, 
//                { "101",0, "Do Cao Hoc", "7000",new JRadioButton() },
//                { "101",0, "Do Cao Hoc", "7000",new JRadioButton() },
//                { "101",0, "Do Cao Hoc", "7000",new JRadioButton() },
//                { "101", 0,"Do Cao Hoc", "7000",new JRadioButton() },
//                { "101", 0,"Do Cao Hoc", "7000",new JRadioButton() },
//                { "101", 0,"Do Cao Hoc", "7000",new JRadioButton() },              
//        };
        
//        
        Object data[][] = { 
                { "101", "Tran Van Minh", "6000",new JCheckBox() }, 
                { "102", "Phan Van Tai", "8000",new JCheckBox()  }, 
                { "101", "Do Cao Hoc", "7000",new JCheckBox() },
                { "101", "Do Cao Hoc", "7000",new JCheckBox() },
                { "101", "Do Cao Hoc", "7000",new JCheckBox() },
                { "101", "Do Cao Hoc", "7000",new JCheckBox() },
                { "101", "Do Cao Hoc", "7000",new JCheckBox() },
                { "101", "Do Cao Hoc", "7000",new JCheckBox() },              
        };
        
//        Object data[][] = { 
//                { "101",0, "Tran Van Minh", "6000"}, 
//                { "102",0, "Phan Van Tai", "8000"}, 
//                { "101",0, "Do Cao Hoc", "7000"},             
//        };
// 
//        JTable jt = new JTable(data, column);
//        jt.setBounds(30, 40, 200, 300);
// 
//        JScrollPane sp = new JScrollPane(jt);
//        pnlDanhSachPhong.add(sp);
 
        String col[] = {"Tên phòng","Loại phòng","Giá phòng/Giờ","Chon"};
        DefaultTableModel model = new DefaultTableModel(col,0);
        model.setDataVector(data, col);
        TableCustomCheckBox table = new TableCustomCheckBox(model);
//        TableCustom table = new TableCustom(model);
//        TableCustomRadio table = new TableCustomRadio(model);
//Spinner
//        TableColumnModel tcm = table.getColumnModel();
//        TableColumn tc = tcm.getColumn(1);
//        tc.setCellEditor(new SpinnerEditor());
        JScrollPane sp = new JScrollPane(table);
//test
        table.addEvent(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("1");
            }  
        });
        System.err.println(table.getRowCount());
        table.fixTable(sp);
        pnlDanhSachPhong.add(sp,"w 100%,h 100%");
        pnlInfo.add(pnlDanhSachPhong,"w 70%,h 100%");
    }
    
    public void initForm(){
        MainPanel.setLayout(new MigLayout("","20[center]20"));
//        MainPanel.setBackground(Color.WHITE);
        
        pnlInfo = new PanelShadow();
        pnlInfo.setLayout(new MigLayout("", "20[center] 20 [center]20", "20[]10"));
        initOldRoomInfo();
        initNewRoom();
        pnlInfo.setBackground(Color.WHITE);
        
        pnlAction = new JPanel();
        pnlAction.setBackground(Color.LIGHT_GRAY);
            
        MainPanel.add(pnlInfo,"w 100%,h 30%,wrap");
        MainPanel.add(pnlAction,"w 100%,h 340");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    // End of variables declaration//GEN-END:variables
}
