/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import gui.swing.panel.PanelShadow;
import gui.swing.button.Button;
import gui.swing.table.TableCustomCheckBox;
import gui.swing.table.TableCustomRadio;
import gui.swing.textfield.MyTextField;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JSeparator;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author 84975
 */
public class GD_DoiPhong extends javax.swing.JDialog {
private TableCustomCheckBox table;
    private JPanel pnlLoc;
    private JPanel pnlDanhSachPhong;
    private JPanel pnlInfo;
    private JPanel pnlHieuChinh;
    private String fontName = "sansserif";
    private int fontPlain = Font.PLAIN;
    private int font16 = 16;
    private int font14 = 14;
    private int font12 = 12;
    private Color colorBtn = new Color(184, 238, 241);
    private Color colorLabel = new Color(47, 72, 210);

    /**
     * Creates new form GD_CuaSoDatPhong2
     */
    public GD_DoiPhong() {
        setModal(true);
        initComponents();
        setSize(new Dimension(1350,540));
        setLocation(150, 150);
        setTitle("Đổi phòng");
        initForm();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GD_DoiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GD_DoiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GD_DoiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GD_DoiPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GD_DoiPhong dialog = new GD_DoiPhong();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    
    public void initOldRoomInfo(){
        pnlLoc = new JPanel();
        pnlLoc.setLayout(new MigLayout("","30[][]","10[]5"));
        
        JLabel lblPhongCu = new JLabel("Phòng cũ");
        lblPhongCu.setFont(new Font(fontName, fontPlain, font16));
        lblPhongCu.setForeground(colorLabel);
        pnlLoc.add(lblPhongCu, "span, w 100%, h 30!, wrap");
        
        JLabel lblTenPhong = new JLabel("Ngày giờ đặt :");
        lblTenPhong.setFont(new Font(fontName, fontPlain, font14));
        pnlLoc.add(lblTenPhong, "align right");

        MyTextField txtTenPhong = new MyTextField();
        txtTenPhong.setFont(new Font(fontName, fontPlain, font14));
        txtTenPhong.setEnabled(false);
        txtTenPhong.setBorderLine(true);
        pnlLoc.add(txtTenPhong, "w 100:260:350, h 36! , wrap");
        
        JLabel lblLoaiPhong = new JLabel("Loại phòng :");
        lblLoaiPhong.setFont(new Font(fontName, fontPlain, font14));
        pnlLoc.add(lblLoaiPhong, "align right");

        MyTextField txtLoaiPhong = new MyTextField();
        txtLoaiPhong.setFont(new Font(fontName, fontPlain, font14));
        txtLoaiPhong.setEnabled(false);
        txtLoaiPhong.setBorderLine(true);
        pnlLoc.add(txtLoaiPhong, "w 100:260:350, h 36! , wrap");
        
        JLabel lblGiaPhong = new JLabel("Giá phòng :");
        lblGiaPhong.setFont(new Font(fontName, fontPlain, font14));
        pnlLoc.add(lblGiaPhong, "align right");

        MyTextField txtGiaPhong = new MyTextField();
        txtGiaPhong.setFont(new Font(fontName, fontPlain, font14));
        txtGiaPhong.setEnabled(false);
        txtGiaPhong.setBorderLine(true);
        pnlLoc.add(txtGiaPhong, "w 100:260:350, h 36! , wrap");
        
        JLabel lblGioDaHat = new JLabel("Giờ đã hát :");
        lblGioDaHat.setFont(new Font(fontName, fontPlain, font14));
        pnlLoc.add(lblGioDaHat, "align right");

        MyTextField txtGioDaHat = new MyTextField();
        txtGioDaHat.setFont(new Font(fontName, fontPlain, font14));
        txtGioDaHat.setEnabled(false);
        txtGioDaHat.setBorderLine(true);
        
        pnlLoc.add(txtGioDaHat, "w 100:260:350, h 36! , wrap");
        
        JLabel lblTongTienCu = new JLabel("Tổng tiền :");
        lblTongTienCu.setFont(new Font(fontName, fontPlain, font14));
        pnlLoc.add(lblTongTienCu, "align right");

        MyTextField txtTongTienCu = new MyTextField();
        txtTongTienCu.setFont(new Font(fontName, fontPlain, font14));
        txtTongTienCu.setEnabled(false);
        txtTongTienCu.setBorderLine(true);
       
        
        pnlLoc.add(txtTongTienCu, "w 100:260:300, h 36! , wrap");
        pnlInfo.add(pnlLoc,"w 35%,h 100%");
        pnlLoc.setBackground(Color.WHITE);  
        
        JSeparator spr = new JSeparator(SwingConstants.VERTICAL);
        spr.setPreferredSize(new Dimension(20, 250));
        pnlInfo.add(spr);

    }
    
    public void initNewRoom(){
        pnlDanhSachPhong = new JPanel();
        pnlDanhSachPhong.setOpaque(false);
        
        pnlDanhSachPhong.setLayout(new MigLayout("","[]","10[]10"));
            pnlDanhSachPhong.setBackground(Color.WHITE);    
            
        JLabel lblPhongMoi = new JLabel("Thông tin các phòng có thể đổi");
        lblPhongMoi.setFont(new Font(fontName, fontPlain, font16));
        lblPhongMoi.setForeground(colorLabel);
        pnlDanhSachPhong.add(lblPhongMoi, "span, w 100%, h 30!, wrap");
        
        Object data[][] = { 
                { "101", "Tran Van Minh", "6000",new JRadioButton() }, 
                { "102", "Phan Van Tai", "8000",new JRadioButton()  }, 
                { "101","Do Cao Hoc", "7000",new JRadioButton() },
                { "101", "Do Cao Hoc", "7000",new JRadioButton() },
                { "101", "Do Cao Hoc", "7000",new JRadioButton() },
                { "101","Do Cao Hoc", "7000",new JRadioButton() },
                { "101","Do Cao Hoc", "7000",new JRadioButton() },
                { "101","Do Cao Hoc", "7000",new JRadioButton() },              
        };
        
//        
//        Object data[][] = { 
//                { "101", "Tran Van Minh", "6000",new JCheckBox() }, 
//                { "102", "Phan Van Tai", "8000",new JCheckBox()  }, 
//                { "101", "Do Cao Hoc", "7000",new JCheckBox() },
//                { "101", "Do Cao Hoc", "7000",new JCheckBox() },
//                { "101", "Do Cao Hoc", "7000",new JCheckBox() },
//                { "101", "Do Cao Hoc", "7000",new JCheckBox() },
//                { "101", "Do Cao Hoc", "7000",new JCheckBox() },
//                { "101", "Do Cao Hoc", "7000",new JCheckBox() },              
//        };
        
//        Object data[][] = { 
//                { "101",0, "Tran Van Minh", "6000"}, 
//                { "102",0, "Phan Van Tai", "8000"}, 
//                { "101",0, "Do Cao Hoc", "7000"},             
//        };
// 
//        JTable jt = new JTable(data, column);
//        jt.setBounds(30, 40, 200, 300);
// 
//        JScrollPane sp = new JScrollPane(jt);
//        pnlDanhSachPhong.add(sp);
 
        String col[] = {"Tên phòng","Loại phòng","Giá phòng/Giờ","Chon"};
        DefaultTableModel model = new DefaultTableModel(col,0);
        model.setDataVector(data, col);
//        TableCustomCheckBox table = new TableCustomCheckBox(model);
//        TableCustom table = new TableCustom(model);
        TableCustomRadio table = new TableCustomRadio(model);
//Spinner
//        TableColumnModel tcm = table.getColumnModel();
//        TableColumn tc = tcm.getColumn(1);
//        tc.setCellEditor(new SpinnerEditor());
        JScrollPane sp = new JScrollPane(table);
//test
        table.addEvent(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("1");
            }  
        });
        System.err.println(table.getRowCount());
        table.fixTable(sp);
        pnlDanhSachPhong.add(sp,"w 100%,h 100%");
        pnlInfo.add(pnlDanhSachPhong,"w 65%,h 100%");
    }
    
    public void initNewRoomInfo(){

        JPanel pnlThongTin = new JPanel();
        pnlThongTin.setLayout(new MigLayout("","15[][]","10[]5"));
        
        JLabel lblKhachHang = new JLabel("Khách Hàng :");
        lblKhachHang.setFont(new Font(fontName, fontPlain, font14));
        pnlThongTin.add(lblKhachHang, "align right");

        MyTextField txtKhachHang = new MyTextField();
        txtKhachHang.setFont(new Font(fontName, fontPlain, font14));
        txtKhachHang.setEnabled(false);
        txtKhachHang.setBorderLine(true);
        pnlThongTin.add(txtKhachHang, "w 100:260:350, h 36! , wrap");
        
        JLabel lblLoaiPhong = new JLabel("Loại phòng mới :");
        lblLoaiPhong.setFont(new Font(fontName, fontPlain, font14));
        pnlThongTin.add(lblLoaiPhong, "align right");

        MyTextField txtLoaiPhong = new MyTextField();
        txtLoaiPhong.setFont(new Font(fontName, fontPlain, font14));
        txtLoaiPhong.setEnabled(false);
        txtLoaiPhong.setBorderLine(true);
        pnlThongTin.add(txtLoaiPhong, "w 100:260:350, h 36! , wrap");
        
        JLabel lblGioDatDau = new JLabel("Giờ bắt đầu :");
        lblGioDatDau.setFont(new Font(fontName, fontPlain, font14));
        pnlThongTin.add(lblGioDatDau, "align right");

        MyTextField txtGioBatDau = new MyTextField();
        txtGioBatDau.setFont(new Font(fontName, fontPlain, font14));
        txtGioBatDau.setEnabled(false);
        txtGioBatDau.setBorderLine(true);
        pnlThongTin.add(txtGioBatDau, "w 100:260:350, h 36! , wrap");
        
        pnlThongTin.setBackground(Color.WHITE);
           
        JPanel pnlButton = new JPanel();
        pnlButton.setLayout(new MigLayout("","push[]10[]20","push[]10"));
        pnlButton.setBackground(Color.WHITE);
        Button btnHuy = new Button("Hủy đổi phòng");
        btnHuy.setFont(new Font(fontName, fontPlain, font14));
        btnHuy.setBackground(colorBtn);
        Button btnDoiPhong = new Button("đổi phòng");
        btnDoiPhong.setFont(new Font(fontName, fontPlain, font14));
        btnDoiPhong.setBackground(colorBtn);
        
        pnlButton.add(btnHuy,"h 36!");
        pnlButton.add(btnDoiPhong,"h 36!");
        
        pnlHieuChinh.add(pnlThongTin,"w 40%");
        pnlHieuChinh.add(pnlButton,"w 60%,h 80%");
    }
    
    public void initForm(){
        MainPanel.setLayout(new MigLayout("","20[center]10"));
//        MainPanel.setBackground(Color.WHITE);
        
        pnlInfo = new PanelShadow();
        pnlInfo.setLayout(new MigLayout("", "20[center][center]20", "20[]10"));
        pnlInfo.setBackground(Color.WHITE);
        
        pnlHieuChinh = new PanelShadow();
        pnlHieuChinh.setLayout(new MigLayout("", "20[]20[]","10[]"));
        pnlHieuChinh.setBackground(Color.WHITE);
        
        
        initOldRoomInfo();
        initNewRoom();
        initNewRoomInfo();
        
    
        MainPanel.add(pnlInfo,"w 100%,h 30%,wrap");
        MainPanel.add(pnlHieuChinh,"w 100%,h 240");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    // End of variables declaration//GEN-END:variables
}
