/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import gui.swing.button.Button;
import gui.swing.textfield.MyTextField;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JLabel;

import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Hao
 */
public class GD_DanhSachPhong extends JPanel {

    /**
     * Creates new form GD_DanhSachPhong
     */
     public GD_DanhSachPhong(){
         initComponents();
         buildGD();
    }

    public void buildGD() {
        String fontName = "sansserif";
        int fontStyle = Font.PLAIN;
        int fontSize = 16;
        Color colorBtn = new Color(184, 238, 241);
        
        pnlTop.setPreferredSize(new Dimension(1119, 200));
        pnlTop.setLayout(new MigLayout());
        
        /**
         * Begin: group thông tin phòng
         */
        JPanel pnlThongTin = new JPanel();
        pnlThongTin.setOpaque(false);
        pnlThongTin.setLayout(new MigLayout("fill", "push[center]10[center]20[center]10[]push", "push[center]20[center]20[]push"));
        pnlTop.add(pnlThongTin,"w 100%,h 70%, wrap");
        
        //Mã phòng
        JLabel lblMaPhong = new JLabel("Mã phòng:");
        lblMaPhong.setFont(new Font(fontName, fontStyle, fontSize));
        pnlThongTin.add(lblMaPhong, "align right");
        
        JTextField txtMaPhong = new MyTextField();
        txtMaPhong.setFont(new Font(fontName, fontStyle, fontSize));
        pnlThongTin.add(txtMaPhong, "w 30%, h 36!");
        
        //Loại phòng
        JLabel lblLoaiPhong = new JLabel("Loại phòng:");
        lblLoaiPhong.setFont(new Font(fontName, fontStyle, fontSize));
        pnlThongTin.add(lblLoaiPhong, "align right");
        
        JComboBox<String> cmbLoaiPhong = new JComboBox<>();
        cmbLoaiPhong.setFont(new Font(fontName, fontStyle, fontSize));
        cmbLoaiPhong.addItem("Loại phòng");
        pnlThongTin.add(cmbLoaiPhong, "w 30%, h 36!, wrap");
        
        //Tên phòng
        JLabel lblTenPhong = new JLabel("Tên phòng:");
        lblTenPhong.setFont(new Font(fontName, fontStyle, fontSize));
        pnlThongTin.add(lblTenPhong, "align right");
        
        JTextField txtTenPhong = new MyTextField();
        txtTenPhong.setFont(new Font(fontName, fontStyle, fontSize));
        pnlThongTin.add(txtTenPhong, "w 30%, h 36!, wrap");
        
        //   Panel nút chức năng
        JPanel pnlButton = new JPanel();
        pnlButton.setOpaque(false);
        pnlButton.setLayout(new MigLayout());
        pnlTop.add(pnlButton, "align right,w 50%, h 30%");

        // Nút Thêm
        Button btnThemPhong = new Button("Thêm");
        btnThemPhong .setFont(new Font(fontName, fontStyle, fontSize));
        btnThemPhong .setBackground(colorBtn);
        pnlButton.add(btnThemPhong , "w 100!, h 36!, gap 0 20px");//, growx

        // Nút Xóa
        Button btnXoaPhong  = new Button("Xóa");
        btnXoaPhong .setFont(new Font(fontName, fontStyle, fontSize));
        btnXoaPhong .setBackground(colorBtn);
        pnlButton.add(btnXoaPhong , "w 100!, h 36!, gap 0 20px");

        // Nút Sửa
        Button btnSuaPhong  = new Button("Sửa");
        btnSuaPhong .setFont(new Font(fontName, fontStyle, fontSize));
        btnSuaPhong .setBackground(colorBtn);
        pnlButton.add(btnSuaPhong , "w 100!, h 36!, gap 0 20px");

        // Nút Làm mới
        Button btnLamMoi = new Button("Làm mới");
        btnLamMoi.setFont(new Font(fontName, fontStyle, fontSize));
        btnLamMoi.setBackground(colorBtn);
        pnlButton.add(btnLamMoi, "w 100!, h 36!");
        /**
         * end: group thông tin phòng hát
         */
         /*Begin: group danh sách Phòng hát*/
        pnlBottom.setLayout(new MigLayout());

        pnlBottom.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.gray, 2), "Danh sách khách hàng", TitledBorder.LEFT, TitledBorder.TOP, new Font("sansserif", Font.PLAIN, 16), Color.gray));

        pnlBottom.setPreferredSize(new Dimension(1119, 1110));
        /*End: group danh sách Phòng */
        
        setPreferredSize(new Dimension(1119, 1500));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new gui.panel.PanelShadow();
        pnlBottom = new gui.panel.PanelShadow();
        lblTitle = new javax.swing.JLabel();

        pnlTop.setBackground(new java.awt.Color(255, 255, 255));
        pnlTop.setShadowOpacity(0.3F);
        pnlTop.setShadowSize(3);
        pnlTop.setShadowType(gui.dropshadow.ShadowType.TOP);

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        pnlBottom.setBackground(new java.awt.Color(255, 255, 255));
        pnlBottom.setShadowOpacity(0.3F);
        pnlBottom.setShadowSize(3);
        pnlBottom.setShadowType(gui.dropshadow.ShadowType.TOP);

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        lblTitle.setFont(new java.awt.Font("SansSerif", 0, 16)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(4, 72, 210));
        lblTitle.setText("Danh Sách Phòng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(0, 993, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    private gui.panel.PanelShadow pnlBottom;
    private gui.panel.PanelShadow pnlTop;
    // End of variables declaration//GEN-END:variables
}
